export async function seedCaseStudies(prisma: any) {
  const caseStudies = [
    {
      title: "Revolutionizing Telehealth: 10x User Growth",
      slug: "revolutionizing-telehealth",
      client: "MediCare Plus",
      industry: "Health",
      problem: "The client had a clunky legacy system that deterred elderly patients from booking remote appointments.",
      research: "Conducted 50+ user interviews with seniors to understand friction points in the booking flow.",
      strategy: "Redesign the UX from the ground up focusing on accessibility, large touch targets, and simplified navigation.",
      execution: "Implemented a React Native mobile application and a Next.js web dashboard with a custom design system.",
      solution: "A seamlessly integrated telehealth platform that allows one-click booking and high-quality video consultations.",
      results: "Increased monthly active users by 1000% and reduced booking abandonment rate by 85%.",
      timeline: "6 months",
      servicesUsed: ["UX/UI Design", "Mobile Development", "Web Development"],
      metrics: [{ label: "User Growth", value: "10x" }, { label: "Abandonment", value: "-85%" }],
      beforeAndAfter: { before: "Complex 7-step booking process", after: "Simple 2-step booking process" },
      testimonial: "M4Y completely transformed our patient experience. The new platform is intuitive and our patients love it.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "SaaS Enterprise Churn Reduction",
      slug: "saas-enterprise-churn-reduction",
      client: "CloudSync Pro",
      industry: "SaaS",
      problem: "High customer churn due to a steep learning curve and complex onboarding process.",
      research: "Analyzed user session recordings and identified drop-off points during the first 5 minutes of usage.",
      strategy: "Introduce an interactive, gamified onboarding sequence and contextual tooltips.",
      execution: "Developed a custom onboarding flow using React and integrated it with their existing monolithic backend.",
      solution: "A guided, step-by-step product tour that educates users while they perform their first tasks.",
      results: "Reduced churn by 40% and increased Day 1 retention by 65%.",
      timeline: "3 months",
      servicesUsed: ["UX Research", "Frontend Development"],
      metrics: [{ label: "Churn Reduction", value: "-40%" }, { label: "D1 Retention", value: "+65%" }],
      beforeAndAfter: { before: "Text-heavy documentation", after: "Interactive product tour" },
      testimonial: "Our users finally understand the value of our product immediately after signing up.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "E-commerce Conversion Rate Optimization",
      slug: "ecommerce-cro-success",
      client: "Luxe Retail",
      industry: "E-commerce",
      problem: "High traffic but low conversion rate on product pages due to slow load times and poor mobile UX.",
      research: "Performed A/B testing on 5 different product page layouts and audited site performance.",
      strategy: "Migrate to a headless commerce architecture using Next.js and Shopify to drastically improve speed.",
      execution: "Rebuilt the frontend, implemented server-side rendering, and optimized all media assets.",
      solution: "A blazing fast, mobile-first e-commerce storefront with a seamless checkout experience.",
      results: "Increased conversion rate from 1.2% to 3.8% and reduced page load time by 3 seconds.",
      timeline: "4 months",
      servicesUsed: ["Headless Commerce", "Performance Optimization"],
      metrics: [{ label: "Conversion Rate", value: "3.16x" }, { label: "Load Time", value: "-3s" }],
      beforeAndAfter: { before: "Monolithic, slow Magento store", after: "Fast Next.js headless storefront" },
      testimonial: "Sales skyrocketed after the relaunch. The speed difference is night and day.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "FinTech App Scaling to 1M Users",
      slug: "fintech-app-scaling",
      client: "PayStream",
      industry: "FinTech",
      problem: "The legacy backend couldn't handle the load of a rapidly growing user base, causing frequent downtimes.",
      research: "Load tested the existing infrastructure and identified database bottlenecks and inefficient API calls.",
      strategy: "Migrate to a microservices architecture and implement robust caching mechanisms.",
      execution: "Rewrote critical services in Go and deployed them on Kubernetes, while utilizing Redis for caching.",
      solution: "A highly available, scalable backend architecture capable of processing thousands of transactions per second.",
      results: "Successfully scaled to 1M+ users with 99.99% uptime and zero latency issues.",
      timeline: "8 months",
      servicesUsed: ["Backend Architecture", "Cloud Infrastructure"],
      metrics: [{ label: "Uptime", value: "99.99%" }, { label: "Active Users", value: "1M+" }],
      beforeAndAfter: { before: "Frequent timeouts during peak hours", after: "Seamless handling of 10k TPS" },
      testimonial: "M4Y's engineering team saved our platform. We can now scale confidently without fear of crashing.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "AI-Powered Logistics Routing",
      slug: "ai-logistics-routing",
      client: "Swift Freight",
      industry: "Logistics",
      problem: "Inefficient delivery routes leading to high fuel costs and delayed shipments.",
      research: "Analyzed historical GPS data and traffic patterns to identify optimization opportunities.",
      strategy: "Develop a custom machine learning model to predict traffic and optimize routes in real-time.",
      execution: "Trained a predictive model using Python and TensorFlow, integrated into a custom dispatcher dashboard.",
      solution: "An intelligent routing engine that dynamically adjusts paths based on real-time data.",
      results: "Reduced fuel consumption by 22% and improved on-time delivery rates by 15%.",
      timeline: "5 months",
      servicesUsed: ["AI/ML Development", "Data Engineering"],
      metrics: [{ label: "Fuel Savings", value: "22%" }, { label: "On-time Delivery", value: "+15%" }],
      beforeAndAfter: { before: "Manual route planning", after: "Automated AI-driven routing" },
      testimonial: "The AI routing system has fundamentally changed our cost structure for the better.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "EdTech Platform Personalization",
      slug: "edtech-platform-personalization",
      client: "LearnSmart",
      industry: "EdTech",
      problem: "Low student engagement due to a one-size-fits-all curriculum.",
      research: "Conducted learning style assessments on 500 students to segment the user base.",
      strategy: "Implement an adaptive learning engine that tailors content based on student performance.",
      execution: "Built a recommendation system and a dynamic UI that adjusts difficulty levels in real-time.",
      solution: "A personalized learning experience where every student receives a unique curriculum path.",
      results: "Increased student course completion rates by 50% and boosted average test scores.",
      timeline: "6 months",
      servicesUsed: ["Full-Stack Development", "Data Science"],
      metrics: [{ label: "Completion Rate", value: "+50%" }, { label: "Test Scores", value: "+12%" }],
      beforeAndAfter: { before: "Static curriculum", after: "Adaptive personalized learning paths" },
      testimonial: "Students are far more engaged, and the results speak for themselves.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "Real Estate Virtual Tours",
      slug: "real-estate-virtual-tours",
      client: "Prime Properties",
      industry: "Real Estate",
      problem: "Low conversion on luxury property listings due to out-of-town buyers being unable to visit.",
      research: "Surveyed international buyers to understand their primary concerns when buying unseen properties.",
      strategy: "Integrate immersive, interactive 3D virtual tours into all luxury property listings.",
      execution: "Developed a WebGL-based viewer integrated seamlessly into their existing React website.",
      solution: "A photorealistic 3D tour experience allowing users to 'walk' through properties from anywhere.",
      results: "Increased remote sales by 35% and doubled average time spent on property pages.",
      timeline: "3 months",
      servicesUsed: ["3D Rendering", "Web Development"],
      metrics: [{ label: "Remote Sales", value: "+35%" }, { label: "Time on Page", value: "2x" }],
      beforeAndAfter: { before: "Static photo galleries", after: "Interactive 3D virtual tours" },
      testimonial: "Our clients are making multi-million dollar decisions based on these incredible virtual tours.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "AI Chatbot for Customer Support",
      slug: "ai-chatbot-support",
      client: "TechGadget Inc",
      industry: "Retail",
      problem: "Overwhelmed support team with a backlog of repetitive inquiries.",
      research: "Analyzed 10,000+ support tickets to categorize the most common issues.",
      strategy: "Deploy an NLP-based chatbot to handle Tier 1 support requests autonomously.",
      execution: "Built a custom chatbot using OpenAI's API and integrated it with Zendesk.",
      solution: "An intelligent assistant capable of resolving 60% of tickets without human intervention.",
      results: "Reduced average response time from 4 hours to 2 minutes and cut support costs by 40%.",
      timeline: "2 months",
      servicesUsed: ["AI Integration", "API Development"],
      metrics: [{ label: "Response Time", value: "-99%" }, { label: "Support Costs", value: "-40%" }],
      beforeAndAfter: { before: "4 hour average response time", after: "2 minute average response time" },
      testimonial: "The chatbot has freed up our agents to handle complex issues. It's a game changer.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "Cybersecurity Compliance Automation",
      slug: "cybersecurity-compliance-automation",
      client: "SecureBank",
      industry: "FinTech",
      problem: "Manual compliance auditing was slow, expensive, and prone to human error.",
      research: "Interviewed compliance officers to map out the entire manual auditing workflow.",
      strategy: "Automate data collection and report generation using a centralized dashboard.",
      execution: "Developed a secure internal portal that automatically pulls logs from various AWS services.",
      solution: "A real-time compliance monitoring tool that generates audit-ready reports instantly.",
      results: "Reduced auditing time by 80% and achieved 100% compliance accuracy.",
      timeline: "7 months",
      servicesUsed: ["Security Engineering", "Backend Development"],
      metrics: [{ label: "Audit Time", value: "-80%" }, { label: "Accuracy", value: "100%" }],
      beforeAndAfter: { before: "Manual spreadsheet tracking", after: "Automated real-time dashboard" },
      testimonial: "We save thousands of hours a year on audits thanks to this automated system.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "Travel App Rebranding & UX Overhaul",
      slug: "travel-app-rebranding",
      client: "Wanderlust",
      industry: "Travel",
      problem: "Outdated design and confusing navigation led to poor app store reviews and high uninstall rates.",
      research: "Conducted usability testing with current users to identify major pain points in the UI.",
      strategy: "A complete visual rebrand and restructuring of the app's information architecture.",
      execution: "Designed a modern, vibrant UI and rebuilt the iOS and Android apps using Flutter.",
      solution: "A beautiful, intuitive travel booking app with a streamlined user journey.",
      results: "Boosted app store rating from 2.8 to 4.7 stars and increased bookings by 45%.",
      timeline: "4 months",
      servicesUsed: ["Branding", "Mobile App Development", "UI/UX Design"],
      metrics: [{ label: "App Rating", value: "4.7" }, { label: "Bookings", value: "+45%" }],
      beforeAndAfter: { before: "Cluttered, outdated UI", after: "Modern, streamlined mobile experience" },
      testimonial: "The new design is stunning. Our users love it, and our revenue reflects that.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "IoT Dashboard for Smart Agriculture",
      slug: "iot-smart-agriculture",
      client: "AgriTech Solutions",
      industry: "Agriculture",
      problem: "Farmers had no centralized way to view data from hundreds of soil and weather sensors.",
      research: "Visited farms to understand how agricultural workers interact with technology in the field.",
      strategy: "Create a mobile-friendly, high-contrast dashboard for outdoor use that aggregates sensor data.",
      execution: "Built a Vue.js progressive web app (PWA) with offline capabilities.",
      solution: "A robust dashboard providing real-time alerts and actionable insights on crop health.",
      results: "Improved crop yields by 12% and reduced water usage by 30% through precise irrigation.",
      timeline: "5 months",
      servicesUsed: ["IoT Integration", "Frontend Development"],
      metrics: [{ label: "Crop Yield", value: "+12%" }, { label: "Water Saved", value: "30%" }],
      beforeAndAfter: { before: "Fragmented sensor apps", after: "Unified, actionable dashboard" },
      testimonial: "I can monitor my entire farm from my phone, even without a cell signal.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "Decentralized Finance (DeFi) Platform",
      slug: "defi-platform-launch",
      client: "YieldCoin",
      industry: "Web3",
      problem: "Needed a secure and user-friendly platform for staking and yield farming.",
      research: "Analyzed existing DeFi platforms to identify common security flaws and UX issues.",
      strategy: "Prioritize security with rigorous smart contract audits while maintaining a clean, Web2-like UI.",
      execution: "Developed smart contracts in Solidity and a React frontend integrated with Web3.js.",
      solution: "A secure, intuitive DeFi dashboard that abstract away blockchain complexities for the user.",
      results: "Secured $50M in Total Value Locked (TVL) within the first month of launch.",
      timeline: "6 months",
      servicesUsed: ["Blockchain Development", "Smart Contract Auditing", "Frontend Development"],
      metrics: [{ label: "TVL", value: "$50M" }, { label: "Security Breaches", value: "0" }],
      beforeAndAfter: { before: "Complex CLI tools", after: "Simple, intuitive web interface" },
      testimonial: "M4Y delivered a platform that is both incredibly secure and easy for our community to use.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "Energy Grid Monitoring System",
      slug: "energy-grid-monitoring",
      client: "EcoPower",
      industry: "Energy",
      problem: "Delays in identifying power grid failures led to prolonged outages.",
      research: "Studied grid topology and the latency of existing monitoring infrastructure.",
      strategy: "Implement a real-time event streaming architecture to process sensor data instantly.",
      execution: "Utilized Apache Kafka and a Node.js microservices backend to handle high-throughput data.",
      solution: "A centralized command center that visualizes grid health and predicts failures before they happen.",
      results: "Reduced average outage response time by 60% and prevented 15 major blackouts.",
      timeline: "9 months",
      servicesUsed: ["Data Engineering", "Backend Development"],
      metrics: [{ label: "Response Time", value: "-60%" }, { label: "Blackouts Prevented", value: "15" }],
      beforeAndAfter: { before: "Reactive maintenance", after: "Predictive, real-time monitoring" },
      testimonial: "We now have complete visibility into our grid, allowing us to act proactively.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "Automotive Dealership Management System",
      slug: "auto-dealership-management",
      client: "DriveAuto",
      industry: "Automotive",
      problem: "Dealerships were using outdated, disparate software for sales, inventory, and servicing.",
      research: "Interviewed dealership managers, salespeople, and mechanics to map their daily workflows.",
      strategy: "Consolidate all operations into a single, cloud-based ERP solution.",
      execution: "Developed a comprehensive SaaS platform using Ruby on Rails and PostgreSQL.",
      solution: "An all-in-one management suite that tracks inventory, manages CRM, and schedules services.",
      results: "Increased dealership efficiency by 30% and boosted cross-departmental sales by 15%.",
      timeline: "12 months",
      servicesUsed: ["Enterprise Software Development", "UI/UX Design"],
      metrics: [{ label: "Efficiency", value: "+30%" }, { label: "Sales Increase", value: "+15%" }],
      beforeAndAfter: { before: "3 different legacy systems", after: "1 unified cloud platform" },
      testimonial: "This software has completely streamlined how our dealerships operate.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "Food Delivery App Optimization",
      slug: "food-delivery-optimization",
      client: "QuickBite",
      industry: "FoodTech",
      problem: "High delivery times due to inefficient order batching and routing.",
      research: "Analyzed thousands of delivery routes and order times to find bottlenecks.",
      strategy: "Implement an algorithmic batching system that groups nearby orders efficiently.",
      execution: "Developed a custom algorithm in Python and integrated it into the dispatcher app.",
      solution: "An automated dispatch system that assigns multi-order deliveries to drivers seamlessly.",
      results: "Reduced average delivery time by 8 minutes and increased driver earnings by 20%.",
      timeline: "4 months",
      servicesUsed: ["Algorithm Design", "Backend Development"],
      metrics: [{ label: "Delivery Time", value: "-8 mins" }, { label: "Driver Earnings", value: "+20%" }],
      beforeAndAfter: { before: "Manual order assignment", after: "Automated algorithmic batching" },
      testimonial: "Faster deliveries mean happier customers and happier drivers.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "Fitness Tracking Wearable Integration",
      slug: "fitness-wearable-integration",
      client: "FitLife",
      industry: "Health & Fitness",
      problem: "The client's app couldn't sync data from the newest generation of smartwatches.",
      research: "Reviewed API documentation for Apple HealthKit and Google Fit.",
      strategy: "Build a robust, unified middleware to handle data synchronization across all devices.",
      execution: "Developed a syncing engine that runs in the background and resolves data conflicts.",
      solution: "Seamless integration that instantly updates user health metrics regardless of the wearable used.",
      results: "Increased daily active users by 25% and received zero data syncing complaints.",
      timeline: "2 months",
      servicesUsed: ["Mobile App Development", "API Integration"],
      metrics: [{ label: "DAU", value: "+25%" }, { label: "Sync Errors", value: "0" }],
      beforeAndAfter: { before: "Manual data entry", after: "Automatic, background syncing" },
      testimonial: "Our users love that their workouts finally sync automatically without any hassle.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "Streaming Platform Video Infrastructure",
      slug: "streaming-video-infrastructure",
      client: "ViewPlay",
      industry: "Entertainment",
      problem: "Users were experiencing buffering issues during high-traffic live events.",
      research: "Profiled the existing video delivery pipeline and identified CDN configuration flaws.",
      strategy: "Overhaul the video transcoding pipeline and implement adaptive bitrate streaming (ABR).",
      execution: "Set up AWS MediaLive and integrated a multi-CDN strategy for optimal delivery.",
      solution: "A highly resilient video infrastructure that scales automatically based on viewership.",
      results: "Supported a record 2 million concurrent viewers with zero buffering incidents.",
      timeline: "5 months",
      servicesUsed: ["Video Engineering", "Cloud Infrastructure"],
      metrics: [{ label: "Concurrent Viewers", value: "2M" }, { label: "Buffering Issues", value: "0" }],
      beforeAndAfter: { before: "Frequent buffering during spikes", after: "Flawless HD live streaming" },
      testimonial: "M4Y ensured our biggest live event of the year went off without a single hitch.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "B2B Supply Chain Portal",
      slug: "b2b-supply-chain-portal",
      client: "GlobalTrade Corp",
      industry: "Logistics",
      problem: "Suppliers lacked visibility into inventory levels, leading to frequent stockouts.",
      research: "Conducted workshops with key suppliers to understand their data requirements.",
      strategy: "Build a secure, extranet portal providing real-time inventory and forecasting data.",
      execution: "Developed a React frontend backed by a secure GraphQL API connected to their ERP.",
      solution: "A self-service portal where suppliers can track orders, view forecasts, and manage shipments.",
      results: "Reduced stockouts by 45% and decreased supplier support calls by 70%.",
      timeline: "6 months",
      servicesUsed: ["Web Development", "API Design"],
      metrics: [{ label: "Stockouts", value: "-45%" }, { label: "Support Calls", value: "-70%" }],
      beforeAndAfter: { before: "Email-based inventory updates", after: "Real-time self-service portal" },
      testimonial: "The portal has transformed our relationship with suppliers, making operations incredibly smooth.",
      isFeatured: false,
      status: "PUBLISHED"
    },
    {
      title: "Insurance Claims Processing Automation",
      slug: "insurance-claims-automation",
      client: "SafeGuard Insurance",
      industry: "FinTech / Insurance",
      problem: "Processing claims manually took weeks, frustrating customers and inflating administrative costs.",
      research: "Mapped the entire claims lifecycle to identify the most time-consuming manual steps.",
      strategy: "Implement Optical Character Recognition (OCR) and machine learning to automate document review.",
      execution: "Integrated AWS Textract and custom validation logic to process standard claims instantly.",
      solution: "An automated pipeline that approves low-risk claims without human intervention.",
      results: "Reduced average claim processing time from 14 days to 4 hours.",
      timeline: "7 months",
      servicesUsed: ["AI/ML Development", "Process Automation"],
      metrics: [{ label: "Processing Time", value: "4 hours" }, { label: "Admin Costs", value: "-35%" }],
      beforeAndAfter: { before: "14-day manual review cycle", after: "4-hour automated processing" },
      testimonial: "Our customer satisfaction scores have never been higher thanks to the rapid payouts.",
      isFeatured: true,
      status: "PUBLISHED"
    },
    {
      title: "HR Tech Employee Engagement App",
      slug: "hr-employee-engagement",
      client: "TalentHub",
      industry: "SaaS / HR",
      problem: "Remote teams were feeling disconnected, leading to low morale and high turnover.",
      research: "Surveyed 1,000 remote workers to discover what drives workplace connection and satisfaction.",
      strategy: "Design a social, gamified internal platform focused on peer recognition and wellness.",
      execution: "Built a cross-platform mobile app using React Native with real-time chat and leaderboards.",
      solution: "A vibrant digital workspace where employees can celebrate wins and participate in challenges.",
      results: "Increased employee retention by 18% and saw 85% weekly active usage among staff.",
      timeline: "4 months",
      servicesUsed: ["Mobile App Development", "UI/UX Design"],
      metrics: [{ label: "Retention", value: "+18%" }, { label: "Weekly Active", value: "85%" }],
      beforeAndAfter: { before: "Isolated remote workers", after: "Highly engaged digital community" },
      testimonial: "The app has completely revitalized our company culture across all our remote offices.",
      isFeatured: false,
      status: "PUBLISHED"
    }
  ];

  for (const study of caseStudies) {
    await prisma.caseStudy.create({ data: study });
  }
}
